### ISSUE TITLE
Font use in CSS

### ISSUE THREAD

**Issue by dubinsky** [dubinsky/podval-docbook-gradle#6]
How do I import fonts used in the HTML files?

**Comment by KevinBrt** [comment]
Hi !
You can use, @font-face, in your css file 
`@font-face {
   font-family: test;
   src: url(sansation_light.woff);
}
`

**Comment by dubinsky** [comment]
Wow! That was fast!
Thanks!

**Comment by dubinsky** [comment]
Added to docBook.css and README.md
